$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
    end

    # config.vm.define "mysqldb" do |mysql|
    #     mysql.vm.network "forwarded_port", guest: 3306, host: 3306
    #     mysql.vm.network "public_network", ip: '192.168.0.114'

    #     mysql.vm.provision "shell", inline: "cat /configs/id_rsa.pub >> .ssh/authorized_keys"
    #     mysql.vm.provision "shell", inline: $script_mysql
    #     mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    #     mysql.vm.provision "shell", inline: "service mysql restart"

    #     mysql.vm.synced_folder ".", "/vagrant", disabled: true
    #     mysql.vm.synced_folder "./configs", "/configs"
    # end

    config.vm.define "phpweb" do |phpweb|
        phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
        phpweb.vm.network "public_network", ip: '192.168.0.115'
        phpweb.vm.provision "shell", inline: "apt-get update && apt-get install -y puppet"

        phpweb.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = 'Ubuntu PHPWeb'
        end

        phpweb.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "./configs/manifests"
            puppet.manifest_file = "phpweb.pp"
        end
    end

    config.vm.define "mysqlserver" do |mysqlserver|
        mysqlserver.vm.network "forwarded_port", guest: 3306, host: 3306
        mysqlserver.vm.network "public_network", ip: '192.168.0.116'

        mysqlserver.vm.provision "shell",
            inline: "cat /vagrant/configs/id_rsa.pub >> .ssh/authorized_keys"
    end

    config.vm.define "ansible" do |ansible|
        ansible.vm.network "public_network", ip: '192.168.0.117'

        ansible.vm.provision "shell",
            inline: "cp /vagrant/id_rsa  /home/vagrant && \
                     chmod 600 /home/vagrant/id_rsa"

        ansible.vm.provision "shell", 
            inline: "apt update && \
                     apt install -y software-properties-common && \
                     add-apt-repository --yes --update ppa:ansible/ansible && \
                     apt install -y ansible"

        ansible.vm.provision "shell",
            inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                     /vagrant/configs/ansible/playbook.yml"
    end

    config.vm.define "memcached" do |memcached|
        memcached.vm.box = "centos/7"

        memcached.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = 'Centos7 MemCached'
        end
    end
end